In [18]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [3]:
url = "https://quotes.toscrape.com/"
request = requests.get(url)
request

In [4]:
html = BeautifulSoup(request.content, "html.parser")

In [7]:
quotes_html = html.find("span", {"class": "text"})
print(quotes_html.text)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

In [15]:
quotes = []
for quote_html in html.find_all("span", {"class": "text"}):
    quotes.append(quote_html.text)
quotes

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”',
 '“It is our choices, Harry, that show what we truly are, far more than our abilities.”',
 '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
 '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”',
 "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”",
 '“Try not to become a man of success. Rather become a man of value.”',
 '“It is better to be hated for what you are than to be loved for what you are not.”',
 "“I have not failed. I've just found 10,000 ways that won't work.”",
 "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”",
 '“A day without sunshine is like, you know, night.”']

In [16]:
authors = []
for author_html in html.find_all("small", {"class": "author"}):
    authors.append(author_html.text)
authors

['Albert Einstein',
 'J.K. Rowling',
 'Albert Einstein',
 'Jane Austen',
 'Marilyn Monroe',
 'Albert Einstein',
 'André Gide',
 'Thomas A. Edison',
 'Eleanor Roosevelt',
 'Steve Martin']

In [20]:
df = pd.DataFrame(quotes, index=authors)
df

                                                                   0
Albert Einstein    “The world as we have created it is a process ...
J.K. Rowling       “It is our choices, Harry, that show what we t...
Albert Einstein    “There are only two ways to live your life. On...
Jane Austen        “The person, be it gentleman or lady, who has ...
Marilyn Monroe     “Imperfection is beauty, madness is genius and...
Albert Einstein    “Try not to become a man of success. Rather be...
André Gide         “It is better to be hated for what you are tha...
Thomas A. Edison   “I have not failed. I've just found 10,000 way...
Eleanor Roosevelt  “A woman is like a tea bag; you never know how...
Steve Martin       “A day without sunshine is like, you know, nig...

In [21]:
df.loc["Albert Einstein"]

                                                                 0
Albert Einstein  “The world as we have created it is a process ...
Albert Einstein  “There are only two ways to live your life. On...
Albert Einstein  “Try not to become a man of success. Rather be...

In [24]:
wh_html = requests.get("https://www.willhaben.at/iad/kaufen-und-verkaufen/marktplatz/armbanduhren-2651?isNavigation=true&srcType=vertical-browse&srcAdd=2651&sfId=e89b26f0-3f08-4d42-9bc9-588b59d135e8&rows=90&page=1")

In [25]:
wh = BeautifulSoup(wh_html.content, "html.parser")

In [43]:
data_raw = wh.find("script", {"id": "__NEXT_DATA__"}).text

In [50]:
import json
data = json.loads(data_raw)
search_results = data["props"]["pageProps"]["searchResult"]["advertSummaryList"]["advertSummary"]

In [53]:
from pprint import  pprint
for result in search_results:
    pprint(result)
    break

{'adTypeId': 67,
 'advertImageList': {'advertImage': [{'description': 'Cover Image',
                                      'id': 1,
                                      'mainImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_-1526604220_hoved.jpg',
                                      'name': '5/108/065/5745_-1526604220.jpg',
                                      'reference': '5/108/065/5745_-1526604220.jpg',
                                      'referenceImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_-1526604220.jpg',
                                      'selfLink': 'https://api.willhaben.at/restapi/v2/atimage/1080655745/1',
                                      'similarImageSearchUrl': None,
                                      'thumbnailImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_-1526604220_thumb.jpg'},
                                     {'description': 'Cover Image',
                                      'id': 1,
                                      'mainImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_898428054_hoved.jpg',
                                      'name': '5/108/065/5745_898428054.jpg',
                                      'reference': '5/108/065/5745_898428054.jpg',
                                      'referenceImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_898428054.jpg',
                                      'selfLink': 'https://api.willhaben.at/restapi/v2/atimage/1080655745/1',
                                      'similarImageSearchUrl': None,
                                      'thumbnailImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_898428054_thumb.jpg'},
                                     {'description': 'Cover Image',
                                      'id': 1,
                                      'mainImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_-490740008_hoved.jpg',
                                      'name': '5/108/065/5745_-490740008.jpg',
                                      'reference': '5/108/065/5745_-490740008.jpg',
                                      'referenceImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_-490740008.jpg',
                                      'selfLink': 'https://api.willhaben.at/restapi/v2/atimage/1080655745/1',
                                      'similarImageSearchUrl': None,
                                      'thumbnailImageUrl': 'https://cache.willhaben.at/mmo/5/108/065/5745_-490740008_thumb.jpg'}],
                     'floorPlans': []},
 'advertStatus': {'description': 'aktiv', 'id': 'active', 'statusId': 50},
 'advertiserInfo': {'iconPNG': None,
                    'iconSVG': None,
                    'iconType': 'NONE',
                    'label': None},
 'attributes': {'attribute': [{'name': 'LOCATION',
                               'values': ['Wien, 10. Bezirk, Favoriten']},
                              {'name': 'p2penabled', 'values': ['true']},
                              {'name': 'CHANGED', 'values': ['1769769480000']},
                              {'name': 'categorytreeattributeids',
                               'values': ['[2600;3536, 5007850;5007851, '
                                          '2535;2537, 2535;2536, 2549;2550, '
                                          '21;2546]']},
                              {'name': 'CHANGED_String',
                               'values': ['2026-01-30T11:38:00Z']},
                              {'name': 'POSTCODE', 'values': ['1100']},
                              {'name': 'BODY_DYN',
                               'values': ['Versace-Armbanduhr. sechs Monate '
                                          'alt. Preis 200€']},
                              {'name': 'STATE', 'values': ['Wien']},
                              {'name': 'ORG_UUID',
                               'values': ['897ef704-3e0f-4d8a-884f-e2c91a4831c9']},
                              {'name': 'HEADING',
                               'values': ['Versus Versace Armbanduhren']},
                              {'name': 'DISTRICT', 'values': ['Wien']},
                              {'name': 'PUBLISHED',
                               'values': ['1769769480000']},
                              {'name': 'COUNTRY', 'values': ['Österreich']},
                              {'name': 'PRICE/AMOUNT', 'values': ['60.0']},
                              {'name': 'ENDDATE_String',
                               'values': ['2026-03-16T11:38:00Z']},
                              {'name': 'ADTYPE_ID', 'values': ['67']},
                              {'name': 'ADID', 'values': ['1080655745']},
                              {'name': 'ORGID', 'values': ['23142539']},
                              {'name': 'SEGMENT', 'values': ['1']},
                              {'name': 'SEO_URL',
                               'values': ['kaufen-und-verkaufen/d/versus-versace-armbanduhren-1080655745/']},
                              {'name': 'ALL_IMAGE_URLS',
                               'values': ['5/108/065/5745_-1526604220.jpg;5/108/065/5745_898428054.jpg;5/108/065/5745_-490740008.jpg']},
                              {'name': 'PUBLISHED_String',
                               'values': ['2026-01-30T11:38:00Z']},
                              {'name': 'ISPRIVATE', 'values': ['1']},
                              {'name': 'categorytreeids',
                               'values': ['2409;2650;2651']},
                              {'name': 'PRODUCT_ID', 'values': ['67']},
                              {'name': 'MMO',
                               'values': ['5/108/065/5745_-1526604220.jpg']},
                              {'name': 'ENDDATE', 'values': ['1773657480000']},
                              {'name': 'AD_UUID',
                               'values': ['343c5a73-b703-4476-b600-b34e9d305250']},
                              {'name': 'ADDRESS',
                               'values': ['Favoritenstrasse']},
                              {'name': 'COORDINATES',
                               'values': ['48.16764,16.38097']},
                              {'name': 'PRICE', 'values': ['60']},
                              {'name': 'PRICE_FOR_DISPLAY', 'values': ['€ 60']},
                              {'name': 'DOES_NOT_COME_FROM_SEARCH_ENGINE__TEASER_ATTRIBUTE',
                               'values': ['Andere Marken']},
                              {'name': 'TEASER_ATTRIBUTE',
                               'values': ['Andere Marken']}]},
 'children': None,
 'contextLinkList': {'contextLink': [{'description': 'Identifies this entity',
                                      'id': 'selfLink',
                                      'relativePath': '/atverz/1080655745',
                                      'selected': False,
                                      'serviceName': 'iad',
                                      'uri': 'https://api.willhaben.at/restapi/v2/atverz/1080655745'},
                                     {'description': 'Self reference',
                                      'id': 'seoSelfLink',
                                      'relativePath': '/atverz/kaufen-und-verkaufen/d/versus-versace-armbanduhren-1080655745/',
                                      'selected': False,
                                      'serviceName': 'iad',
                                      'uri': 'https://api.willhaben.at/restapi/v2/atverz/kaufen-und-verkaufen/d/versus-versace-armbanduhren-1080655745/'},
                                     {'description': 'Self reference to advert '
                                                     'via ad detail component',
                                      'id': 'adDetailLink',
                                      'relativePath': '/1080655745',
                                      'selected': False,
                                      'serviceName': 'addetail',
                                      'uri': 'https://publicapi.willhaben.at/atdetail/v1/1080655745'},
                                     {'description': 'Remove ad from any '
                                                     'folder',
                                      'id': 'removeAdFromFolder',
                                      'relativePath': '/userfolders/remove/1080655745',
                                      'selected': False,
                                      'serviceName': 'iad',
                                      'uri': 'https://api.willhaben.at/restapi/v2/userfolders/remove/1080655745'},
                                     {'description': 'Get contextlinks to save '
                                                     'the ad in the users '
                                                     'folders',
                                      'id': 'getFolderSaveLinks',
                                      'relativePath': '/userfolders/links/1080655745',
                                      'selected': False,
                                      'serviceName': 'iad',
                                      'uri': 'https://api.willhaben.at/restapi/v2/userfolders/links/1080655745'},
                                     {'description': 'Share link in iAd',
                                      'id': 'iadShareLink',
                                      'relativePath': '/iad/object?adId=1080655745',
                                      'selected': False,
                                      'serviceName': 'web_url',
                                      'uri': 'https://www.willhaben.at/iad/object?adId=1080655745'}]},
 'description': 'Versus Versace Armbanduhren',
 'id': '1080655745',
 'productId': 67,
 'selfLink': 'https://api.willhaben.at/restapi/v2/atverz/1080655745',
 'teaserAttributes': [],
 'upsellingOrganisationLogo': None,
 'verticalId': 5}