In [2]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

In [3]:
url = "https://quotes.toscrape.com/"
request = requests.get(url)
request

In [4]:
html = BeautifulSoup(request.content, "html.parser")

In [7]:
quotes_html = html.find("span", {"class": "text"})
print(quotes_html.text)

“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”

In [15]:
quotes = []
for quote_html in html.find_all("span", {"class": "text"}):
    quotes.append(quote_html.text)
quotes

['“The world as we have created it is a process of our thinking. It cannot be changed without changing our thinking.”',
 '“It is our choices, Harry, that show what we truly are, far more than our abilities.”',
 '“There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.”',
 '“The person, be it gentleman or lady, who has not pleasure in a good novel, must be intolerably stupid.”',
 "“Imperfection is beauty, madness is genius and it's better to be absolutely ridiculous than absolutely boring.”",
 '“Try not to become a man of success. Rather become a man of value.”',
 '“It is better to be hated for what you are than to be loved for what you are not.”',
 "“I have not failed. I've just found 10,000 ways that won't work.”",
 "“A woman is like a tea bag; you never know how strong it is until it's in hot water.”",
 '“A day without sunshine is like, you know, night.”']

In [16]:
authors = []
for author_html in html.find_all("small", {"class": "author"}):
    authors.append(author_html.text)
authors

['Albert Einstein',
 'J.K. Rowling',
 'Albert Einstein',
 'Jane Austen',
 'Marilyn Monroe',
 'Albert Einstein',
 'André Gide',
 'Thomas A. Edison',
 'Eleanor Roosevelt',
 'Steve Martin']

In [20]:
df = pd.DataFrame(quotes, index=authors)
df

                                                                   0
Albert Einstein    “The world as we have created it is a process ...
J.K. Rowling       “It is our choices, Harry, that show what we t...
Albert Einstein    “There are only two ways to live your life. On...
Jane Austen        “The person, be it gentleman or lady, who has ...
Marilyn Monroe     “Imperfection is beauty, madness is genius and...
Albert Einstein    “Try not to become a man of success. Rather be...
André Gide         “It is better to be hated for what you are tha...
Thomas A. Edison   “I have not failed. I've just found 10,000 way...
Eleanor Roosevelt  “A woman is like a tea bag; you never know how...
Steve Martin       “A day without sunshine is like, you know, nig...

In [21]:
df.loc["Albert Einstein"]

                                                                 0
Albert Einstein  “The world as we have created it is a process ...
Albert Einstein  “There are only two ways to live your life. On...
Albert Einstein  “Try not to become a man of success. Rather be...

In [3]:
wh_html = requests.get("https://www.willhaben.at/iad/kaufen-und-verkaufen/marktplatz/armbanduhren-2651?isNavigation=true&srcType=vertical-browse&srcAdd=2651&sfId=e89b26f0-3f08-4d42-9bc9-588b59d135e8&rows=90&page=1")

In [4]:
wh = BeautifulSoup(wh_html.content, "html.parser")

In [5]:
data_raw = wh.find("script", {"id": "__NEXT_DATA__"}).text

In [17]:
import json
data = json.loads(data_raw)
search_results = data["props"]["pageProps"]["searchResult"]["advertSummaryList"]["advertSummary"]

{"props":{"pageProps":{"searchResult":{"id":301,"description":"Alle Anzeigen","heading":"Anzeigen in Armbanduhren - Uhren","verticalId":5,"searchId":301,"rowsRequested":90,"rowsFound":83842,"rowsReturned":90,"pageRequested":1,"searchDate":"2026-02-06T11:37:47+0100","lastUserAlertViewedDate":null,"newAdsSeparatorPosition":null,"advertSummaryList":{"advertSummary":[{"id":"919594505","verticalId":5,"adTypeId":67,"productId":67,"advertStatus":{"id":"active","description":"aktiv","statusId":50},"description":"Michael Kors Damenuhr","attributes":{"attribute":[{"name":"LOCATION","values":["Wien, 10. Bezirk, Favoriten"]},{"name":"p2penabled","values":["false"]},{"name":"CHANGED","values":["1770374160000"]},{"name":"categorytreeattributeids","values":["[5007850;5007851, 2535;2537, 2535;2536, 2549;2550, 2600;2625, 21;2546]"]},{"name":"CHANGED_String","values":["2026-02-06T11:36:00Z"]},{"name":"POSTCODE","values":["1100"]},{"name":"BODY_DYN","values":["Michael Kors"]},{"name":"STATE","values":["Wien"]},{"name":"ORG_UUID","values":["1f100f89-d549-4567-8ec9-c82a3667e9e5"]},{"name":"HEADING","values":["Michael Kors Damenuhr"]},{"name":"DISTRICT","values":["Wien"]},{"name":"PUBLISHED","values":["1770374160000"]},{"name":"COUNTRY","values":["Österreich"]},{"name":"PRICE/AMOUNT","values":["170.0"]},{"name":"ENDDATE_String","values":["2026-03-23T11:36:00Z"]},{"name":"ADTYPE_ID","values":["67"]},{"name":"ADID","values":["919594505"]},{"name":"ORGID","values":["19669751"]},{"name":"SEGMENT","values":["1"]},{"name":"SEO_URL","values":["kaufen-und-verkaufen/d/michael-kors-damenuhr-919594505/"]},{"name":"ALL_IMAGE_URLS","values":["5/919/594/505_-1604983244.jpg;5/919/594/505_-1989877154.jpg;5/919/594/505_1425922045.jpg"]},{"name":"PUBLISHED_String","values":["2026-02-06T11:36:00Z"]},{"name":"ISPRIVATE","values":["1"]},{"name":"categorytreeids","values":["2409;2650;2651"]},{"name":"PRODUCT_ID","values":["67"]},{"name":"MMO","values":["5/919/594/505_-1604983244.jpg"]},{"name":"ENDDATE","values":["1774262160000"]},{"name":"AD_UUID","values":["42d4e3ee-fd4b-4425-9db1-b34e9d305250"]},{"name":"PRICE","values":["170"]},{"name":"PRICE_FOR_DISPLAY","values":["€ 170"]},{"name":"DOES_NOT_COME_FROM_SEARCH_ENGINE__TEASER_ATTRIBUTE","values":["Michael Kors"]},{"name":"TEASER_ATTRIBUTE","values":["Michael Kors"]}]},"advertImageList":{"advertImage":[{"id":1,"name":"5/919/594/505_-1604983244.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/919594505/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_-1604983244_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_-1604983244_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_-1604983244.jpg","similarImageSearchUrl":null,"reference":"5/919/594/505_-1604983244.jpg"},{"id":1,"name":"5/919/594/505_-1989877154.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/919594505/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_-1989877154_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_-1989877154_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_-1989877154.jpg","similarImageSearchUrl":null,"reference":"5/919/594/505_-1989877154.jpg"},{"id":1,"name":"5/919/594/505_1425922045.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/919594505/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_1425922045_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_1425922045_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/5/919/594/505_1425922045.jpg","similarImageSearchUrl":null,"reference":"5/919/594/505_1425922045.jpg"}],"floorPlans":[]},"selfLink":"https://api.willhaben.at/restapi/v2/atverz/919594505","contextLinkList":{"contextLink":[{"id":"selfLink","description":"Identifies this entity","uri":"https://api.willhaben.at/restapi/v2/atverz/919594505","selected":false,"relativePath":"/atverz/919594505","serviceName":"iad"},{"id":"seoSelfLink","description":"Self reference","uri":"https://api.willhaben.at/restapi/v2/atverz/kaufen-und-verkaufen/d/michael-kors-damenuhr-919594505/","selected":false,"relativePath":"/atverz/kaufen-und-verkaufen/d/michael-kors-damenuhr-919594505/","serviceName":"iad"},{"id":"adDetailLink","description":"Self reference to advert via ad detail component","uri":"https://publicapi.willhaben.at/atdetail/v1/919594505","selected":false,"relativePath":"/919594505","serviceName":"addetail"},{"id":"removeAdFromFolder","description":"Remove ad from any folder","uri":"https://api.willhaben.at/restapi/v2/userfolders/remove/919594505","selected":false,"relativePath":"/userfolders/remove/919594505","serviceName":"iad"},{"id":"getFolderSaveLinks","description":"Get contextlinks to save the ad in the users folders","uri":"https://api.willhaben.at/restapi/v2/userfolders/links/919594505","selected":false,"relativePath":"/userfolders/links/919594505","serviceName":"iad"},{"id":"iadShareLink","description":"Share link in iAd","uri":"https://www.willhaben.at/iad/object?adId=919594505","selected":false,"relativePath":"/iad/object?adId=919594505","serviceName":"web_url"}]},"advertiserInfo":{"label":null,"iconSVG":null,"iconPNG":null,"iconType":"NONE"},"upsellingOrganisationLogo":null,"teaserAttributes":[{"prefix":null,"value":null,"postfix":"Michael Kors"}],"children":null},{"id":"1352957367","verticalId":5,"adTypeId":67,"productId":67,"advertStatus":{"id":"active","description":"aktiv","statusId":50},"description":"Omega Genève - Vintage 1960","attributes":{"attribute":[{"name":"LOCATION","values":["Haag am Hausruck"]},{"name":"p2penabled","values":["false"]},{"name":"CHANGED","values":["1770374160000"]},{"name":"categorytreeattributeids","values":["[5007850;5007851, 2535;2537, 2549;2551, 21;23, 2535;2536, 2600;2627]"]},{"name":"CHANGED_String","values":["2026-02-06T11:36:00Z"]},{"name":"POSTCODE","values":["4680"]},{"name":"BODY_DYN","values":["Ich liebe diese wunderschöne Uhr, aber leider brauche ich im Moment Geld und habe mich deshalb entschieden, sie zu verkaufen. Omega Genève – Vintage 1960 Durchmesser: 35 / 36 mm Referenznummer: 135.070 Werk: ETA AS1130 Zustand: sehr sauber und gepflegt..."]},{"name":"STATE","values":["Oberösterreich"]},{"name":"ORG_UUID","values":["eeec6d8d-51f5-405e-b859-c82a3667e9e5"]},{"name":"HEADING","values":["Omega Genève - Vintage 1960"]},{"name":"DISTRICT","values":["Grieskirchen"]},{"name":"PUBLISHED","values":["1770374160000"]},{"name":"COUNTRY","values":["Österreich"]},{"name":"PRICE/AMOUNT","values":["450.0"]},{"name":"ENDDATE_String","values":["2026-03-23T11:36:00Z"]},{"name":"ADTYPE_ID","values":["67"]},{"name":"ADID","values":["1352957367"]},{"name":"ORGID","values":["27154528"]},{"name":"SEGMENT","values":["1"]},{"name":"SEO_URL","values":["kaufen-und-verkaufen/d/omega-geneve-vintage-1960-1352957367/"]},{"name":"PUBLISHED_String","values":["2026-02-06T11:36:00Z"]},{"name":"ISPRIVATE","values":["1"]},{"name":"categorytreeids","values":["2409;2650;2651"]},{"name":"PRODUCT_ID","values":["67"]},{"name":"ENDDATE","values":["1774262160000"]},{"name":"AD_UUID","values":["e139b4b9-713b-41f7-94b3-b34e9d305250"]},{"name":"PRICE","values":["450"]},{"name":"PRICE_FOR_DISPLAY","values":["€ 450"]},{"name":"DOES_NOT_COME_FROM_SEARCH_ENGINE__TEASER_ATTRIBUTE","values":["Omega"]},{"name":"TEASER_ATTRIBUTE","values":["Omega"]}]},"advertImageList":{"advertImage":[],"floorPlans":[]},"selfLink":"https://api.willhaben.at/restapi/v2/atverz/1352957367","contextLinkList":{"contextLink":[{"id":"selfLink","description":"Identifies this entity","uri":"https://api.willhaben.at/restapi/v2/atverz/1352957367","selected":false,"relativePath":"/atverz/1352957367","serviceName":"iad"},{"id":"seoSelfLink","description":"Self reference","uri":"https://api.willhaben.at/restapi/v2/atverz/kaufen-und-verkaufen/d/omega-geneve-vintage-1960-1352957367/","selected":false,"relativePath":"/atverz/kaufen-und-verkaufen/d/omega-geneve-vintage-1960-1352957367/","serviceName":"iad"},{"id":"adDetailLink","description":"Self reference to advert via ad detail component","uri":"https://publicapi.willhaben.at/atdetail/v1/1352957367","selected":false,"relativePath":"/1352957367","serviceName":"addetail"},{"id":"removeAdFromFolder","description":"Remove ad from any folder","uri":"https://api.willhaben.at/restapi/v2/userfolders/remove/1352957367","selected":false,"relativePath":"/userfolders/remove/1352957367","serviceName":"iad"},{"id":"getFolderSaveLinks","description":"Get contextlinks to save the ad in the users folders","uri":"https://api.willhaben.at/restapi/v2/userfolders/links/1352957367","selected":false,"relativePath":"/userfolders/links/1352957367","serviceName":"iad"},{"id":"iadShareLink","description":"Share link in iAd","uri":"https://www.willhaben.at/iad/object?adId=1352957367","selected":false,"relativePath":"/iad/object?adId=1352957367","serviceName":"web_url"}]},"advertiserInfo":{"label":null,"iconSVG":null,"iconPNG":null,"iconType":"NONE"},"upsellingOrganisationLogo":null,"teaserAttributes":[{"prefix":null,"value":null,"postfix":"Omega"}],"children":null},{"id":"1845067113","verticalId":5,"adTypeId":67,"productId":67,"advertStatus":{"id":"active","description":"aktiv","statusId":50},"description":"Longines Damenuhr vergoldet","attributes":{"attribute":[{"name":"LOCATION","values":["Wien, 15. Bezirk, Rudolfsheim-Fünfhaus"]},{"name":"p2penabled","values":["true"]},{"name":"CHANGED","values":["1770374160000"]},{"name":"categorytreeattributeids","values":["[2600;2624, 5007850;5007851, 2535;2537, 21;23, 2535;2536, 2549;2550, 5008971;5008972]"]},{"name":"CHANGED_String","values":["2026-02-06T11:36:00Z"]},{"name":"POSTCODE","values":["1150"]},{"name":"BODY_DYN","values":["Damenuhr von Longines, vergoldet, römische Ziffern, Durchmesser Lünette ca 23mm, filigran und klassisch, neues Lederarmband, in Longines-Etui"]},{"name":"STATE","values":["Wien"]},{"name":"ORG_UUID","values":["29e08ee3-bf60-4216-80c6-c82a3667e9e5"]},{"name":"HEADING","values":["Longines Damenuhr vergoldet"]},{"name":"DISTRICT","values":["Wien"]},{"name":"PUBLISHED","values":["1770374160000"]},{"name":"COUNTRY","values":["Österreich"]},{"name":"PRICE/AMOUNT","values":["220.0"]},{"name":"ENDDATE_String","values":["2026-03-23T11:36:00Z"]},{"name":"ADTYPE_ID","values":["67"]},{"name":"ADID","values":["1845067113"]},{"name":"ORGID","values":["23787899"]},{"name":"SEGMENT","values":["1"]},{"name":"SEO_URL","values":["kaufen-und-verkaufen/d/longines-damenuhr-vergoldet-1845067113/"]},{"name":"ALL_IMAGE_URLS","values":["3/184/506/7113_811524233.jpg;3/184/506/7113_1030090105.jpg;3/184/506/7113_-2014128295.jpg;3/184/506/7113_2059527907.jpg;3/184/506/7113_1017763738.jpg"]},{"name":"PUBLISHED_String","values":["2026-02-06T11:36:00Z"]},{"name":"ISPRIVATE","values":["1"]},{"name":"categorytreeids","values":["2409;2650;2651"]},{"name":"PRODUCT_ID","values":["67"]},{"name":"MMO","values":["3/184/506/7113_811524233.jpg"]},{"name":"ENDDATE","values":["1774262160000"]},{"name":"AD_UUID","values":["fd16afd8-0be6-47ca-bc6c-b34e9d305250"]},{"name":"ADDRESS","values":["Stadthalle"]},{"name":"PRICE","values":["220"]},{"name":"PRICE_FOR_DISPLAY","values":["€ 220"]},{"name":"DOES_NOT_COME_FROM_SEARCH_ENGINE__TEASER_ATTRIBUTE","values":["Longines"]},{"name":"TEASER_ATTRIBUTE","values":["Longines"]}]},"advertImageList":{"advertImage":[{"id":1,"name":"3/184/506/7113_811524233.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/1845067113/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_811524233_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_811524233_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_811524233.jpg","similarImageSearchUrl":null,"reference":"3/184/506/7113_811524233.jpg"},{"id":1,"name":"3/184/506/7113_1030090105.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/1845067113/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_1030090105_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_1030090105_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_1030090105.jpg","similarImageSearchUrl":null,"reference":"3/184/506/7113_1030090105.jpg"},{"id":1,"name":"3/184/506/7113_-2014128295.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/1845067113/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_-2014128295_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_-2014128295_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/3/184/506/7113_-2014128295.jpg","similarImageSearchUrl":null,"reference":"3/184/506/7113_-2014128295.jpg"}],"floorPlans":[]},"selfLink":"https://api.willhaben.at/restapi/v2/atverz/1845067113","contextLinkList":{"contextLink":[{"id":"selfLink","description":"Identifies this entity","uri":"https://api.willhaben.at/restapi/v2/atverz/1845067113","selected":false,"relativePath":"/atverz/1845067113","serviceName":"iad"},{"id":"seoSelfLink","description":"Self reference","uri":"https://api.willhaben.at/restapi/v2/atverz/kaufen-und-verkaufen/d/longines-damenuhr-vergoldet-1845067113/","selected":false,"relativePath":"/atverz/kaufen-und-verkaufen/d/longines-damenuhr-vergoldet-1845067113/","serviceName":"iad"},{"id":"adDetailLink","description":"Self reference to advert via ad detail component","uri":"https://publicapi.willhaben.at/atdetail/v1/1845067113","selected":false,"relativePath":"/1845067113","serviceName":"addetail"},{"id":"removeAdFromFolder","description":"Remove ad from any folder","uri":"https://api.willhaben.at/restapi/v2/userfolders/remove/1845067113","selected":false,"relativePath":"/userfolders/remove/1845067113","serviceName":"iad"},{"id":"getFolderSaveLinks","description":"Get contextlinks to save the ad in the users folders","uri":"https://api.willhaben.at/restapi/v2/userfolders/links/1845067113","selected":false,"relativePath":"/userfolders/links/1845067113","serviceName":"iad"},{"id":"iadShareLink","description":"Share link in iAd","uri":"https://www.willhaben.at/iad/object?adId=1845067113","selected":false,"relativePath":"/iad/object?adId=1845067113","serviceName":"web_url"}]},"advertiserInfo":{"label":null,"iconSVG":null,"iconPNG":null,"iconType":"NONE"},"upsellingOrganisationLogo":null,"teaserAttributes":[{"prefix":null,"value":null,"postfix":"Longines"}],"children":null},{"id":"1657815325","verticalId":5,"adTypeId":67,"productId":67,"advertStatus":{"id":"active","description":"aktiv","statusId":50},"description":"ICE Watch","attributes":{"attribute":[{"name":"LOCATION","values":["Ober-Grafendorf"]},{"name":"p2penabled","values":["false"]},{"name":"CHANGED","values":["1770374100000"]},{"name":"categorytreeattributeids","values":["[5007850;5007851, 2535;2537, 2600;2618, 21;23, 2535;2536, 2549;2550]"]},{"name":"CHANGED_String","values":["2026-02-06T11:35:00Z"]},{"name":"POSTCODE","values":["3200"]},{"name":"BODY_DYN","values":["Weiße ICE Watch. Versandkosten 8€"]},{"name":"STATE","values":["Niederösterreich"]},{"name":"ORG_UUID","values":["5c2cb27d-45ba-4327-9c6e-c82a3667e9e5"]},{"name":"HEADING","values":["ICE Watch"]},{"name":"DISTRICT","values":["Sankt Pölten Land"]},{"name":"PUBLISHED","values":["1770374100000"]},{"name":"COUNTRY","values":["Österreich"]},{"name":"PRICE/AMOUNT","values":["0.0"]},{"name":"ENDDATE_String","values":["2026-03-23T11:35:00Z"]},{"name":"ADTYPE_ID","values":["67"]},{"name":"ADID","values":["1657815325"]},{"name":"ORGID","values":["19738692"]},{"name":"SEGMENT","values":["1"]},{"name":"SEO_URL","values":["kaufen-und-verkaufen/d/ice-watch-1657815325/"]},{"name":"ALL_IMAGE_URLS","values":["5/165/781/5325_1168564381.jpg;5/165/781/5325_-489561523.jpg;5/165/781/5325_624880118.jpg"]},{"name":"PUBLISHED_String","values":["2026-02-06T11:35:00Z"]},{"name":"ISPRIVATE","values":["1"]},{"name":"categorytreeids","values":["2409;2650;2651"]},{"name":"PRODUCT_ID","values":["67"]},{"name":"MMO","values":["5/165/781/5325_1168564381.jpg"]},{"name":"ENDDATE","values":["1774262100000"]},{"name":"AD_UUID","values":["50591d9d-e5dd-4b0d-a323-b34e9d305250"]},{"name":"PRICE","values":["0"]},{"name":"PRICE_FOR_DISPLAY","values":["zu verschenken"]},{"name":"DOES_NOT_COME_FROM_SEARCH_ENGINE__TEASER_ATTRIBUTE","values":["Ice watch"]},{"name":"TEASER_ATTRIBUTE","values":["Ice watch"]}]},"advertImageList":{"advertImage":[{"id":1,"name":"5/165/781/5325_1168564381.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/1657815325/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_1168564381_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_1168564381_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_1168564381.jpg","similarImageSearchUrl":null,"reference":"5/165/781/5325_1168564381.jpg"},{"id":1,"name":"5/165/781/5325_-489561523.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/1657815325/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_-489561523_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_-489561523_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_-489561523.jpg","similarImageSearchUrl":null,"reference":"5/165/781/5325_-489561523.jpg"},{"id":1,"name":"5/165/781/5325_624880118.jpg","selfLink":"https://api.willhaben.at/restapi/v2/atimage/1657815325/1","description":"Cover Image","mainImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_624880118_hoved.jpg","thumbnailImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_624880118_thumb.jpg","referenceImageUrl":"https://cache.willhaben.at/mmo/5/165/781/5325_624880118.jpg","similarImageSearchUrl":null,"reference":"5/165/781/5325_624880118.jpg"}],"floorPlans":[]},"selfLink":"https://api.willhaben.at/restapi/v2/atverz/1657815325","contextLinkList":{"contextLink":[{"id":"selfLink","description":"Identifies this entity","uri":"https://api.willhaben.at/restapi/v2/atverz/1657815325","selected":false,"relativePath":"/atverz/1657815325","serviceName":"iad"},{"id":"seoSelfLink","description":"Self reference","uri":"https://api.willhaben.at/restapi/v2/atverz/kaufen-und-verkaufen/d/ice-watch-1657815325/","selected":false,"relativePath":"/atverz/kaufen-und-verkaufen/d/ice-watch-1657815325/","serviceName":"iad"},{"id":"adDetailLink","description":"Self reference to advert via ad detail component","uri":"https://publicapi.willhaben.at/atdetail/v1/1657815325","selected":false,"relativePath":"/1657815325","serviceName":"addetail"},{"id":"removeAdFromFolder","description":"Remove ad from any folder","uri":"https://api.willhaben.at/restapi/v2/userfolders/remove/1657815325","selected":false,"relativePath":"/userfolders/remove/1657815325","serviceName":"iad"},{"id":"getFolderSaveLinks","description":"Get contextlinks to save the ad in the users folders","uri":"https://api.willhaben.at/restapi/v2/userfolders/links/1657815325","selected":false,"relativePath":"/userfolders/links/1657815325","serviceName":"iad"},{"id":"iadShareLink","description":"Share link in iAd","uri":"https://www.willhaben.at/iad/object?adId=1657815325","selected":false,"relativePath":"/iad/object?adId=1657815325","serviceName":"web_url"}]},"advertiserInfo":{"label":null,"iconSVG":null,"iconPNG":null,"iconType":"NONE"},"upsellingOrganisationLogo":null,"teaserAttributes":[{"prefix":null,"value":null,"postfix":"Ice watch"}],"children":null},{"id":"1143446050","verticalId":5,"adTypeId":67,"productId":67,"advertStatus":{"id":"active","description":"aktiv","statusId":50},"description":"ICE Watch","attributes":{"attribute":[{"name":"LOCATION","values":["Buchkirchen"]},{"name":"p2penabled","values":["true"]},{"name":"CHANGED","values":["1770374100000"]},{

In [19]:
from pprint import  pprint
for result in search_results:
    print(result["id"])
print(len(search_results))

919594505
1352957367
1845067113
1657815325
1143446050
1153777290
1694718614
1045398968
1027700505
2109378590
1239180872
1651962945
1724350307
1629824297
844468278
1795930086
1107452220
1074967707
1325845018
1791370263
1379924470
965112428
1885766423
1520130989
1257720548
2079645778
2118801088
812779131
1366907493
1434647234
823284678
1955153109
1553904492
1643358986
1939661523
1010809869
2139239690
1768303789
1183433318
1586268712
1337481306
926336648
1652222526
849843211
1748190834
1875365374
1702763321
1388289447
1856813173
2116311799
779052049
929715751
1740196382
1504387227
2144509738
1643249771
1219321042
2109754454
1065572080
1834189244
1290082646
1355883474
1573484750
1432026351
1461292975
2138957957
1434565686
1195950403
1575130180
974852540
1191107133
801305670
1709386071
886742132
1682071142
2064727637
1218167463
869088903
1988713555
1581548227
901389505
1554412833
2015093822
1838239206
1007166030
1179279415
1962297995
1547165094
1141183213
1211665863
90